### ISSUE TITLE
hi, do you have the code for Hybrid Task Cascade(2019) SPADE(2020) PaDiM(2020)?

### ISSUE THREAD

**Issue by inhaowu** [Burf/TFDetection#1]

**Comment by Burf** [comment]
HTC > tfdet.model.detector.hybrid_task_cascade_rcnn + mask_rcnn_usage(https://github.com/Burf/TFDetection/blob/main/usage/mask_rcnn.ipynb)
SPADE > usage(https://github.com/Burf/TFDetection/blob/main/usage/spade.ipynb)
PaDiM > usage (https://github.com/Burf/TFDetection/blob/main/usage/padim.ipynb)
