### ISSUE TITLE
Error while running notebook train/object_detection - module 'tfdet.dataset.balloon' has no attribute 'load_pipe'

### ISSUE THREAD

**Issue by vijaygill** [Burf/TFDetection#10]
Hi,

Thanks for your hard-work. I tried running the notebook from the latest code, but I get the following error.

Please suggest, Thanks

![image](https://user-images.githubusercontent.com/8999486/213046405-2b008344-ec72-4bb3-adaf-b44d78b84ec0.png)

**Comment by vijaygill** [comment]
It looks like example code needs to be updated after some changes to core code.

It is nearly 1:00 AM here and I am going to sleep. Hopefully I will be able to read your code and try to make changes to example and raise a PR.

Thanks!

**Comment by Burf** [comment]
recommend to use tfdet.dataset.Dataset(or tfdet.dataset.YoloDataset)  and tfdet.dataset.PipeLoader.

#example
```
import functools

import tfdet
import tfdet.dataset.transform as T

tr_path = "./balloon/train/via_region_data.json"
te_path = "./balloon/val/via_region_data.json"
label = tfdet.dataset.balloon.LABEL
image_shape = [640, 640]

tr_dataset = tfdet.dataset.balloon.load_dataset(tr_path, mask = True)
tr_dataset = tfdet.dataset.YoloDataset(tr_dataset, image_shape = image_shape,
                                       transform = [functools.partial(T.filter_annotation, label = label),
                                                    functools.partial(T.label_encode, label = label),
                                                    T.normalize])

te_dataset = tfdet.dataset.balloon.load_dataset(te_path,
                                                transform = [T.load, 
                                                             functools.partial(T.resize, image_shape = image_shape), 
                                                             functools.partial(T.pad, image_shape = image_shape),
                                                             functools.partial(T.filter_annotation, label = label),
                                                             functools.partial(T.label_encode, label = label),
                                                             T.normalize],
                                                mask = True)
tr_pipe = tfdet.dataset.PipeLoader(tr_dataset)
tr_pipe = tfdet.dataset.pipeline.args2dict(tr_pipe)
tr_pipe = tfdet.dataset.pipeline.cast(tr_pipe)
tr_pipe = tfdet.dataset.pipeline.key_map(tr_pipe, batch_size = 16, shuffle = False, prefetch = True)

te_pipe = tfdet.dataset.PipeLoader(te_dataset)
te_pipe = tfdet.dataset.pipeline.args2dict(te_pipe)
te_pipe = tfdet.dataset.pipeline.cast(te_pipe)
te_pipe = tfdet.dataset.pipeline.key_map(te_pipe, batch_size = 16, shuffle = False, prefetch = True)

tr_dataset[0] #(640, 640, 3), (?, 1), (?, 4), (?, 640, 640, 1)
next(iter(tr_pipe)) #(16, 640, 640, 3), (16, ?, 1), (16, ?, 4), (16, ?, 640, 640, 1)

te_dataset[0] #(640, 640, 3), (?, 1), (?, 4), (?, 640, 640, 1)
next(iter(te_pipe)) #(13, 640, 640, 3), (13, ?, 1), (13, ?, 4), (13, ?, 640, 640, 1)
```

**Comment by vijaygill** [comment]
> recommend to use tfdet.dataset.Dataset(or tfdet.dataset.YoloDataset) and tfdet.dataset.PipeLoader.
> 
> #example
> 
> ```
> import functools
> 
> import tfdet
> import tfdet.dataset.transform as T
> 
> tr_path = "./balloon/train/via_region_data.json"
> te_path = "./balloon/val/via_region_data.json"
> label = tfdet.dataset.balloon.LABEL
> image_shape = [640, 640]
> 
> tr_dataset = tfdet.dataset.balloon.load_dataset(tr_path, mask = True)
> tr_dataset = tfdet.dataset.YoloDataset(tr_dataset, image_shape = image_shape,
>                                        transform = [functools.partial(T.filter_annotation, label = label),
>                                                     functools.partial(T.label_encode, label = label),
>                                                     T.normalize])
> 
> te_dataset = tfdet.dataset.balloon.load_dataset(te_path,
>                                                 transform = [T.load, 
>                                                              functools.partial(T.resize, image_shape = image_shape), 
>                                                              functools.partial(T.pad, image_shape = image_shape),
>                                                              functools.partial(T.filter_annotation, label = label),
>                                                              functools.partial(T.label_encode, label = label),
>                                                              T.normalize],
>                                                 mask = True)
> tr_pipe = tfdet.dataset.PipeLoader(tr_dataset)
> tr_pipe = tfdet.dataset.pipeline.args2dict(tr_pipe)
> tr_pipe = tfdet.dataset.pipeline.cast(tr_pipe)
> tr_pipe = tfdet.dataset.pipeline.key_map(tr_pipe, batch_size = 16, shuffle = False, prefetch = True)
> 
> te_pipe = tfdet.dataset.PipeLoader(te_dataset)
> te_pipe = tfdet.dataset.pipeline.args2dict(te_pipe)
> te_pipe = tfdet.dataset.pipeline.cast(te_pipe)
> te_pipe = tfdet.dataset.pipeline.key_map(te_pipe, batch_size = 16, shuffle = False, prefetch = True)
> 
> tr_dataset[0] #(640, 640, 3), (?, 1), (?, 4), (?, 640, 640, 1)
> next(iter(tr_pipe)) #(16, 640, 640, 3), (16, ?, 1), (16, ?, 4), (16, ?, 640, 640, 1)
> 
> te_dataset[0] #(640, 640, 3), (?, 1), (?, 4), (?, 640, 640, 1)
> next(iter(te_pipe)) #(13, 640, 640, 3), (13, ?, 1), (13, ?, 4), (13, ?, 640, 640, 1)
> ```

Thanks! Didn't get a chance to look at the code after last attempt. Most likely I will get a chance during the weekend. I will use your example as guide.

**Comment by vijaygill** [comment]
Hi @Burf

Thanks so much for your help. I was able to train Mask-RCNN on balloon dataset and run predictions too!

```
image_edge_size = 800
image_shape = [image_edge_size, image_edge_size]
tr_batch_size = 1
te_batch_size = 1

tr_path = "./balloon/train/via_region_data.json"
te_path = "./balloon/val/via_region_data.json"

label = tfdet.dataset.balloon.LABEL
n_class = len(label)

def get_dataset(path, shuffle):
    dataset = tfdet.dataset.balloon.load_dataset(path,
                                                    transform = [T.load, 
                                                                 functools.partial(T.resize, image_shape = image_shape), 
                                                                 functools.partial(T.pad, image_shape = image_shape),
                                                                 functools.partial(T.filter_annotation, label = label),
                                                                 functools.partial(T.label_encode, label = label),
                                                                 T.normalize],
                                                    mask = True)
    return dataset

def get_dataset_as_pipeline(path, shuffle):
    dataset = get_dataset(path, shuffle)
    pipe = dataset
    pipe = tfdet.dataset.PipeLoader(dataset, batch_size = tr_batch_size, shuffle = shuffle, prefetch = True, num_parallel_calls = 1)
    pipe = tfdet.dataset.pipeline.args2dict(pipe)
    pipe = tfdet.dataset.pipeline.collect(pipe)
    pipe = tfdet.dataset.pipeline.cast(pipe)
    #pipe = tfdet.dataset.pipeline.key_map(pipe, batch_size = 1, shuffle = shuffle, prefetch = True)
    #pipe = pipe.batch(4).prefetch(4)
    return pipe

tr_pipe = get_dataset_as_pipeline(tr_path, True)
te_pipe = get_dataset_as_pipeline(te_path, True)

```

This works for me.

Notice that I had to pass "num_parallel_calls = 1" to make it work. If I omit that, most of the time, my code would crash randomly. The cause I found out was that sometimes the function "load_iter_data" was called without the index parameter. I have not been able to find the cause yet.

From what I read in your code, it seems it is not a bug in your code. But I need more deep investigation.

Thanks once again as your code will help in learning about Mask-RCNN and FCOS, the two things I have been trying to learn for last few weeks but never got a chance.

It is 1:42 AM but today I did not want another day to pass without reading your code and learning something from it!
