### ISSUE TITLE
Input shape for swin transformer backbone ?

### ISSUE THREAD

**Issue by vlarmet** [Burf/TFDetection#11]
Hi,

First, thanks for this work !
I got an error when a try to build a segmentation model using swin transformer as encoder : 

```
x = tf.keras.layers.Input(shape = (224,224,3))  
feature = tfdet.model.backbone.swin_transformer_tiny_224_w7_1k(x, weights=None)  
```

I got ` AssertionError: input feature has wrong size`.
It's the same with various shapes : (256,256,3), (224,224,1) ... etc

Maybe it's a silly question but I'm fairly new to transformers... 
What should be input shape for swin backbones ? Or I missed an intermediate layer between input and swin ?

**Comment by Burf** [comment]
The number of 'Swin Transformer' backbones has been reduced, so please check the details below.

swin_tiny > The recommended image shape is 224.(224, 448, 672, ...)
swin_small > The recommended image shape is 224.(224, 448, 672, ...)
swin_base > The recommended image shape is 224.(224, 448, 672, ...)

swin_v2_tiny > The recommended image shape is 256.(256, 512, 768, ...)
swin_v2_small > The recommended image shape is 256.(256, 512, 768, ...)
swin_v2_base > The recommended image shape is 256.(256, 512, 768, ...)
