### ISSUE TITLE
train with Swin transformer backbone

### ISSUE THREAD

**Issue by farazBhatti** [Burf/TFDetection#2]
Hi, there is it possible to train it with swin transformer backbone for object detection on MSCOCO dataset. 
Thanks

**Comment by Burf** [comment]
First, please refer to function of tfdet.dataset.coco.
Usage will be updated soon.

**Comment by Burf** [comment]
Proceed by referring to the files below.

tfdetection/usage/dataset/dataset
tfdetection/usage/train/object_detection
