### ISSUE TITLE
multi class object detection tutotial

### ISSUE THREAD

**Issue by avber** [Burf/TFDetection#4]
would be nice to see

thanks

**Comment by Burf** [comment]
Usage will be updated soon.

**Comment by Burf** [comment]
See https://github.com/Burf/TFDetection/blob/main/usage/train/object_detection.ipynb, https://github.com/Burf/TFDetection/blob/main/usage/dataset/dataset.ipynb and https://github.com/Burf/TFDetection/blob/main/usage/model/object_detection.ipynb.
Thanks.
