### ISSUE TITLE
Pascal VOC tfrecords dataset training

### ISSUE THREAD

**Issue by Arix12** [Burf/TFDetection#5]
I have a tfrecords dataset in the Pascal VOC format, is it possible to train with it?

**Comment by Burf** [comment]
import tfdet
import tensorflow_datasets as tfds

pipe = tfds.load("voc/2007", split = tfds.Split.VALIDATION)
pipe = tfdet.dataset.pascal_voc.tfds_to_tfdet(pipe, truncated = True, difficult = False)

out = next(iter(pipe))
x_true, y_true, bbox_true = out #x_true:(375, 500, 3), y_true:(3, 1), bbox_true:(3, 4)
