### ISSUE TITLE
training using tensorflow object detection api format tfrecords

### ISSUE THREAD

**Issue by AidanAbramson** [Burf/TFDetection#7]
Hi,
Is it possible to train using ttfrecords packed with tensorflow object detection api format the same way as COCO and pascal voc?
Thanks.

**Comment by Burf** [comment]
Please refer to the URLs https://github.com/Burf/TFDetection/blob/main/usage/train/object_detection.ipynb, https://github.com/Burf/TFDetection/blob/main/tfdet/dataset/coco.py and https://github.com/Burf/TFDetection/blob/main/tfdet/dataset/pascal_voc.py.

**Comment by Burf** [comment]
For example, CoCo Dataset.
See code snippet below.

import tfdet
import tensorflow_datasets as tfds
pipe = tfds.load("coco/2017", split = tfds.Split.VALIDATION)
pipe = tfdet.dataset.coco.tfds_to_tfdet(pipe, crowd = False)
