### ISSUE TITLE
Training is extremely slow

### ISSUE THREAD

**Issue by Arix12** [Burf/TFDetection#8]
Hi,
I am trying to train an object detection model on my own custom coco dataset (a json file) with about 80,000 300x300 images.
I am using the object_detection example (usage/train/object_detection.ipynb) the only differences are the data loading where I use  tfdet.dataset.coco.load_pipe to load my data and the labels (I have 8 labels).
I am training on an NVIDIA RTX 2080 ti with Ryzen 9 5950X and an SSD.
During training my GPU memory is at 100% and the GPU itself is at an average of 80% usage.
a single epoch with this configuration takes more than 24 hours for reference training yolo-v7 from the official repo with the same data and machine takes around 6 minuets per around.
Is there something I am missing? are those normal training times?
Thanks.

**Comment by Burf** [comment]
Show me the code snippet.

**Comment by Arix12** [comment]
I have found the cause for this behavior I accidentally forgot to remove the 'cache=True' from the key_map function and it made the RAM fill up to the top.
Thanks anyway.

**Comment by Burf** [comment]
cache = True > use ram
cache = "path" > use storage

I recommend you to use storage.

**Comment by Arix12** [comment]
Great thanks!
The usage notebooks are great but there are a lot of great little features like this one that are not covered.
Is there any guide/tutorial that covers those maybe?

**Comment by Burf** [comment]
It's based on tf.data.Dataset, so refer to https://www.tensorflow.org/guide/data.
